language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: ruA2ws8ewF3Sr1RLtC2PbvjDXm2oaI2QoWFboJGUiQ9GbcDkzATFzZ1Vqo9q6sR9VyDf6gaQafUueT3zficWbu+6iZ8gKGNRfGwLMCZdB9VgavlJFhrAlqK0fRLf4sVqEZGQEWlL5T2RL6lbxHF3jqWadxEZrm3gO7x6sD6NV4uhKwO9sSGADdgi+0KinurJ2ojEsBeFmQlWx7exYAa1I4tb2ZYkckx2Ay3g10pi0V5wucNtyW3Uko/oXp+H+eR74ksVJ9L40/2EwxywKHJwqyfiiCl9NJlBBKeonIYASYSLLCHnhtSveqlHXcrHho05f/ySOy1w6HU4YfuCrk5nW8rIZBftXXK0qUC14eGjonXBg/bwZuzbr9pYaw1Z1X4XRFegB4a3e38wG3WyPoHsbXNhaG2mF7sXg0Tj8hvcCblK5hMxf16YaKRgOTEVRKzCik+kVsvX6EuATm0T8yyB9TgAEUEDr/zoRTP33FgS4Qf4gGp5rTMzO15aYXm6zr7tryOZSbFbqQuzsrKzptOQD3cHsfe2rkkUhmFRc+p35q/ZqKZF1jW2zb1jj3hqG2iyBdvC9L5Tnu8vAUBNBePHz43I/CWqUDmsErpC5rgwlYOAbIfX6uMa3ZOQGVeCXgz8iA0dM65+n62LHrVbnhnWeTuQB60gK7OXNkKE5XPTK4E=
  app: cccowdin
  on:
    repo: cyrandy/crowdin
